title: Ekaterina Ilin
description: Astrophysicist | Star-Planet Interactions | Stellar Magnetism
theme: minima
author: Ekaterina Ilin
email: ilin@astron.nl
github_username: ekaterinailin

header_pages:
  - index.md
  - cv.md
  - publications.md
  - talks.md
  


